name: pgchat
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.8.16
  - pip=23.0.1
  - cudatoolkit=11.0
  - pytorch=1.7.1
  - torchvision=0.13.1
  - numpy=1.23.5
  - pip:
      - torch==1.7.1
      - scipy==1.5.2
      - tqdm==4.61.2
      - tensorboardX==1.8
      - protobuf==3.20.1
      - spacy==2.3.5
      - ftfy==5.1
      - attrdict==2.0.1